feat: add changelog action
ansys/pyansys-geometry pull request #1023
Opened 2024-02-28 15:36 UTC by klmcadams

## Description
Add the changelog action to pyansys-geometry

## Issue linked
**Please mention the issue number or describe the problem this pull request addresses.**

## Checklist
- [x] I have tested my changes locally.
- [x] I have added necessary documentation or updated existing documentation.
- [x] I have followed the coding style guidelines of this project.
- [x] I have added appropriate unit tests.
- [x] I have reviewed my changes before submitting this pull request.
- [x] I have linked the issue or issues that are solved to the PR if any.
- [x] I have assigned this PR to myself.
- [x] I have made sure that the title of my PR follows [Conventional commits style](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. ``feat: extrude circle to cylinder``)

2024-02-28 15:59 UTC, PipKat commented on CHANGELOG.md
> +
```suggestion
This project uses [towncrier](https://towncrier.readthedocs.io/) to generate changelogs. You can see the changes for the upcoming release in <https://github.com/ansys/{repo-name}/tree/main/changelog.d/>.

```
We let the link be enough emphasis for a new product, so I removed the italics.

2024-02-28 16:00 UTC, PipKat approved these changes
Minor comments on doc-related changes.

2024-02-29 07:27 UTC, RobPasMue requested changes
It's looking good =) Thanks @klmcadams - I will "request changes" in order to block this PR from merging until the action is merged. Once merged, I will approve.

2024-02-29 07:27 UTC, RobPasMue commented on .github/workflows/label.yml
> +    - uses: ansys/actions/doc-changelog@feat/changelog-action
```suggestion
    - uses: ansys/actions/doc-changelog@main
```

We have to use main - just letting this comment for whenever the action is merged.

2024-02-29 07:27 UTC, RobPasMue commented on pyproject.toml
> +showcontent = true
```suggestion
showcontent = true

```

EOF line missing

2024-02-29 07:27 UTC, RobPasMue commented on doc/changelog.d/changelog_template.jinja
> +{% endif %}
```suggestion
{% endif %}

```
EOF line missing

2024-02-29 07:27 UTC, RobPasMue commented on .github/workflows/label.yml
> +        token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
```suggestion
        token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

```
EOF line missing

2024-03-13 13:43 UTC, RobPasMue approved these changes
LGTM! Let's leave it with ``main`` for now. Once v6 is out I'll do the change. This will also allow you to play with the conventional commits approach =)

2024-03-13 13:43 UTC, merged