feat: testing new static search
ansys/pyansys-geometry pull request #1477
Opened 2024-10-14 12:25 UTC by RobPasMue

TEST PR

2024-10-21 12:35 UTC, jorgepiloto requested changes

2024-10-21 12:35 UTC, jorgepiloto commented on doc/source/conf.py
> +    TITLE,
Minor suggestion. Since we are naming nodes in plural, let's do the same of this one:

```suggestion
    TITLES,
```

2024-10-22 12:14 UTC, Revathyvenugopal162 commented on doc/source/conf.py
> +    "examples/": TITLE + PARAGRAPHS,
```suggestion
    "examples/": TITLES + PARAGRAPHS,
```

2024-10-22 12:15 UTC, Revathyvenugopal162 commented on doc/source/conf.py
> +    PARAGRAPHS,
```suggestion
    PARAGRAPHS,
    TITLES,
```

2024-10-23 08:22 UTC, jorgepiloto commented
I can see the search is indexing new nodes. Despite this, the anchors are not correct @Revathyvenugopal162:

Consider the <http://localhost:8000/api/ansys/geometry/core/sketch/arc/Arc.html> page. If searching for `from_three_points`, the breadcrumbs are:

```console
Arc > Overview        # This one is valid
Arc > Method detail   # This should point to the right anchor
```

However, they should be:

```console
Arc > Overview
Arc > Method detail > from_three_point
```

2024-10-24 11:33 UTC, Revathyvenugopal162 commented
> I can see the search is indexing new nodes. Despite this, the anchors are not correct @Revathyvenugopal162:
> 
> Consider the https://geometry.docs.pyansys.com/version/stable/api/ansys/geometry/core/sketch/arc/Arc.html page. If searching for `from_three_points`, the breadcrumbs are:
> 
> ```
> Arc > Overview        # This one is valid
> Arc > Method detail   # This should point to the right anchor
> ```
> 
> However, they should be:
> 
> ```
> Arc > Overview
> Arc > Method detail > from_three_point
> ```

improved the header and the indexing for api references
![image](https://github.com/user-attachments/assets/e56c8d51-0b50-4c25-9dea-049a803fffd7)

2024-10-24 18:27 UTC, jorgepiloto commented
I edited your comment, @Revathyvenugopal162 by attaching the right image. This is working as expected.

2024-10-28 11:13 UTC, RobPasMue commented
Hi both! What's the status here?

2024-10-28 12:52 UTC, Revathyvenugopal162 commented
> Hi both! What's the status here?

It is working as expected and we will release it with ansys-sphinx-theme 1.2

2024-11-04 14:13 UTC, RobPasMue commented
@Revathyvenugopal162 - now that 1.2 is out, can we get this merged?

2024-11-05 16:11 UTC, Revathyvenugopal162 commented
# closing with release of ansys-spshinx-theme v1.2.0

2024-11-05 16:11 UTC, closed without merging