Feat/add manifest path product launcher
ansys/pyansys-geometry pull request #815
Opened 2023-10-18 11:55 UTC by b-matteo

Adding manifest_path parameters to product (Discovery and SC) local launcher in order to be able to specify a specific version of the apiserver with an other version of the product.
For instance, this allows starting Discovery 2022.1 but using ApiServerAddin 2024.1

Also, fixing the GeometryService folder's name in the unified installer.

2023-10-19 07:57 UTC, RobPasMue commented on src/ansys/geometry/core/connection/product_instance.py
> +    elif manifest_path != None and os.path.exists(manifest_path) == False:
```suggestion
    elif manifest_path != None and not os.path.exists(manifest_path):
```

2023-10-19 07:59 UTC, RobPasMue requested changes
Merge my suggestions, otherwise approved

2023-10-19 12:12 UTC, jonahrb commented on src/ansys/geometry/core/connection/product_instance.py
> +    elif manifest_path != None and os.path.exists(manifest_path) == False:
I'll go one step further and say 😄:
```suggestion
    if manifest_path is not None and os.path.exists(manifest_path):
        return manifest_path
    elif manifest_path is not None and not os.path.exists(manifest_path):
```

2023-10-19 12:15 UTC, RobPasMue commented on src/ansys/geometry/core/connection/product_instance.py
> +    elif manifest_path != None and os.path.exists(manifest_path) == False:
I can only agree with @jonahrb! =)

2023-10-28 06:48 UTC, b-matteo commented on src/ansys/geometry/core/connection/product_instance.py
> +WINDOWS_GEOMETRY_SERVICE_FOLDER = "GeometryService"
I tested it against the last unified installer, it is ideed without the final "s"

2023-10-28 06:51 UTC, b-matteo commented on src/ansys/geometry/core/connection/product_instance.py
> +    elif manifest_path != None and os.path.exists(manifest_path) == False:
Done =)

2023-10-30 07:17 UTC, RobPasMue approved these changes

2023-10-30 07:18 UTC, RobPasMue commented
@kmahajan-cadfem - I just remembered that you were the one proposing the change in the folder name  some time ago. Looks like 24R1 will be shipped with the new folder name. Please verify on your end when the time comes 😃

2023-10-30 07:33 UTC, merged