fix: Default trame visualization in Jupyter environments
ansys/pyansys-geometry pull request #904
Opened 2024-01-03 14:44 UTC by AlejandroFernandezLuces

The default visualization breaks the usage of the plotter in Jupyter environments. When the documentation implementation is ready from PyVista side we should revisit how to generate the interactive plotters, since from now on, we will need "html" for documentation and ideally "trame" for regular Jupyter usage.

2024-01-03 15:26 UTC, RobPasMue commented
Doc build failing - have a look at it. I haven't read the logs yet.

2024-01-04 15:37 UTC, RobPasMue submitted a review, later dismissed

2024-01-04 15:37 UTC, RobPasMue commented on doc/source/conf.py
> +os.environ["DOCUMENTATION_BUILD"] = "true"
```suggestion
os.environ["PYANSYS_GEOMETRY_DOC_BUILD"] = "true"
```

2024-01-04 15:37 UTC, RobPasMue commented on src/ansys/geometry/core/__init__.py
> +DOCUMENTATION_BUILD: bool = os.environ.get("PYGEOMETRY_DOC_BUILD", "false").lower() == "true"
```suggestion
DOCUMENTATION_BUILD: bool = os.environ.get("PYANSYS_GEOMETRY_DOC_BUILD", "false").lower() == "true"
```

2024-01-04 15:38 UTC, RobPasMue approved these changes

2024-01-05 08:48 UTC, RobPasMue approved these changes

2024-01-05 08:51 UTC, RobPasMue requested changes
Why this?

```os.environ["PYDEVD_DISABLE_FILE_VALIDATION"] = "1"```

2024-01-05 08:54 UTC, AlejandroFernandezLuces commented
> Why this?
> 
> `os.environ["PYDEVD_DISABLE_FILE_VALIDATION"] = "1"`

Documentation building is getting frozen, and it throws this warning:
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

I though I might give it a try

2024-01-05 08:55 UTC, RobPasMue commented
> > Why this?
> > `os.environ["PYDEVD_DISABLE_FILE_VALIDATION"] = "1"`
> 
> Documentation building is getting frozen, and it throws this warning:
> 
> ```
> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> ```
> 
> I though I might give it a try

Not remotely... I can't see that log on the workflows.

2024-01-05 10:25 UTC, AlejandroFernandezLuces commented
Documentation looks good now. This should be good to go @RobPasMue

2024-01-05 10:29 UTC, RobPasMue approved these changes

2024-01-05 10:29 UTC, merged