active design sync after repair operations,
ansys/pyansys-geometry pull request #933
Opened 2024-01-17 18:26 UTC by umutsoysalansys

Added read existing design to each fix method and you can see the current flow in the caption below. 

![image](https://github.com/ansys/pyansys-geometry/assets/97195410/f95d7b06-d749-4c40-8509-0bd08694a272)

2024-01-18 07:35 UTC, RobPasMue requested changes
I would also modify the ``fix()`` functions to accept an optional boolean called ``return_design``, that returns the active design for you, so that you do not have to add an extra line of code as a user in case you want it. By default, it should be false. In case it is false, return ``None``.

Please accept the suggestions provided as well and modify wherever I might have missed something based on my comments. Thanks @umutsoysalansys, great work!

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/repair_tools.py
> +    from ansys.geometry.core.modeler import Modeler
Put them into a single if @umutsoysalansys

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        modeler object
Please format properly docstrings. No typos.
```suggestion
        Modeler object.
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        modeler object
```suggestion
        Modeler object.
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        modeler object
```suggestion
        Modeler object.
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        modeler object
```suggestion
        Modeler object.
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        self._modeler.read_existing_design()
Add comments
```suggestion

        # After repair operation we need to sync the active design on the server
        self._modeler.read_existing_design()
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        modeler object
```suggestion
        Modeler object.
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        self._modeler.read_existing_design()
```suggestion

        # After repair operation we need to sync the active design on the server
        self._modeler.read_existing_design()
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        self._modeler.read_existing_design()
```suggestion

        # After repair operation we need to sync the active design on the server
        self._modeler.read_existing_design()
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        Active supporting geometry service instance for design modeling.
```suggestion
        Active supporting Geometry Service instance for design modeling.
```

Geometry Service should be capitalized. Please correct everywhere

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        self._modeler.read_existing_design()
```suggestion

        # After repair operation we need to sync the active design on the server
        self._modeler.read_existing_design()
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        modeler object
```suggestion
        Modeler object.
```

2024-01-18 07:35 UTC, RobPasMue commented on src/ansys/geometry/core/tools/problem_areas.py
> +        self._modeler.read_existing_design()
```suggestion

        # After repair operation we need to sync the active design on the server
        self._modeler.read_existing_design()
```

2024-01-18 20:16 UTC, umutsoysalansys commented
@RobPasMue fix method is already returning an object, return message. Wouldn't it be too confusing with returning and optional design there?

2024-01-18 20:16 UTC, umutsoysalansys commented on src/ansys/geometry/core/tools/repair_tools.py
> +    from ansys.geometry.core.modeler import Modeler
done

2024-01-19 06:54 UTC, RobPasMue commented
I wouldn't say so. Python methods can return multiple arguments. My suggestion:

If design is not requested: ``return (message, None)``
If design requested: ``return (message, design)``.

2024-01-19 06:54 UTC, RobPasMue commented
Also, there are some broken tests. Please look into them.

2024-01-19 22:43 UTC, smereu commented
@RobPasMue @umutsoysalansys @b-matteo I saw the comments about returning a design for a fix operations. I think that it may be useful to have to summarize among us if/how we want to use multiple design in the pyAnsys geometry layer. If I am not mistaken, they mirror the multiple documents in SpaceClaim. As you may know, in Discovery the concept of multiple documents has disappeared (it may come back but there is no immediate plan for it).  Also in SpaceClaim there in assumption that the tools always work on the active document (which in SpaceClaim corresponds to the active window). We seem to have an active document concept here but I would say that a tool should be given a document too (without relying on the active document). I had briefly brought it up with Umut but again, it may be good to be all on the same page on how to deal with it.  I hope that this makes sense!

2024-01-22 07:02 UTC, RobPasMue commented
Hi @smereu - multiple documents are handled according to the backend from the Python client. We verify that you are connecting to either a SpaceClaim or Geometry Service backend before allowing the switch to multiple documents. We can discuss this if you prefer nonetheless.

2024-01-23 09:10 UTC, RobPasMue commented
@umutsoysalansys - there are tests failing. Please fix them whenever you have the chance

2024-02-07 16:35 UTC, umutsoysalansys commented
@RobPasMue @b-matteo Closing this one since we had another change merged to tackle this issue. #https://github.com/ansys/pyansys-geometry/pull/975

2024-02-07 16:35 UTC, closed without merging